---
title: "clutch-modeling"
output: html_document
---
```{r Setup}
library(tidyverse)
library(lubridate)
library(GGally)
library(caret)
library(naivebayes)
library(pROC)

```

```{r Data Cleaning}

 # data cleaning and binary conversion
model_df <- read.csv('/cloud/project/data/processed-data/combined_player_shot_chart_2023.csv') |> 
  select('player', 'qtr', 'time_remaining',
         'result', 'distance_ft', 'lead',
         'player_team_score', 'opponent_team_score',
         'shot_type') |> 
  mutate('sec_remaining' = as.numeric(ms(time_remaining), 'seconds')) |>
  mutate(margin = player_team_score - opponent_team_score,
         result = ifelse(result == 'TRUE', 1, 0),
         lead = ifelse(lead == 'TRUE', 1, 0),
         three_pt = ifelse(shot_type == 3, 1, 0)) |>
  select(-'time_remaining', -'player_team_score',
         -'opponent_team_score', -'lead', -'shot_type')

curry_df <- model_df |> filter(player == 'Curry')
```

```{r Exploratory Data Analysis, fig.width=14, fig.height=11}

 # convert qtrs to numeric features
num_curry_df <- curry_df |>
  select(-'player')
num_curry_df$qtr <- as.numeric(factor(num_curry_df$qtr,
         levels = c('1st Qtr', '2nd Qtr', '3rd Qtr',
                    '4th Qtr', '1st OT', '2nd OT')))
# correlation matrix
ggpairs(num_curry_df, progress = FALSE)
```

```{r Train/Test Split}

set.seed(123)

 # stratified 80/20 split
train_idx <- createDataPartition(num_curry_df$result, p = 0.80, list = FALSE)

train_df <- num_curry_df[train_idx, ]
test_df <- num_curry_df[-train_idx, ]

 # verify stratification
cat("Train set:", nrow(train_df), "rows |",
    round(mean(train_df$result == 1) * 100, 1), "% Successful Shots\n")
cat("Test set: ", nrow(test_df),  "rows |",
    round(mean(test_df$result  == 1) * 100, 1), "% Successful Shots\n")

```
```{r Logistic Regression & Feature Selection(Baseline)}

 # 5 features
model_lr <- glm(result ~ distance_ft + qtr + sec_remaining + margin + three_pt,
                data = train_df,
                family = binomial)
 # feature significance
summary(model_lr)
 #                 Estimate Std. Error z value Pr(>|z|)   
 # distance_ft   -0.0674535  0.0135980  -4.961 7.03e-07 ***
 # qtr           -0.0611919  0.0540645  -1.132 0.257706    
 # sec_remaining  0.0002799  0.0003116   0.898 0.369065    
 # margin         0.0273476  0.0065508   4.175 2.98e-05 ***
 # three_pt       0.6167029  0.2810805   2.194 0.028232 *  
  
probs_lr <- predict(model_lr, newdata = test_df, type = "response")
roc_lr <- roc(test_df$result, probs_lr)
cat("Logistic Regression AUC:", auc(roc_lr), "\n")

 # confusion matrix
preds_lr <- ifelse(probs_lr > 0.5, 1, 0)
confusionMatrix(as.factor(preds_lr), as.factor(test_df$result))

 # 3 features
model_lr <- glm(result ~ distance_ft + margin + three_pt,
                data = train_df,
                family = binomial)

probs_lr <- predict(model_lr, newdata = test_df, type = "response")
roc_lr <- roc(test_df$result, probs_lr)
cat("Logistic Regression AUC:", auc(roc_lr), "\n")

 # confusion matrix
preds_lr <- ifelse(probs_lr > 0.5, 1, 0)
confusionMatrix(as.factor(preds_lr), as.factor(test_df$result))

 # LR feature selection comparison

 # 2 variable (dist, margin)                         Accuracy: 0.59, Kappa: 0.20,  AUC: 0.64, Sensitivity: 0.72, Specificity: 0.47
 # 3 variable (dist, margin, three_pt)               Accuracy: 0.60, Kappa: 0.21,  AUC: 0.64, Sensitivity: 0.76, Specificity: 0.45
 # 4 variable (dist, qtr, sec, margin)               Accuracy: 0.46, Kappa: -0.07, AUC: 0.53, Sensitivity: 0.55, Specificity: 0.38
 # 5 variable (dist, qtr, sec, margin, three_pt)     Accuracy: 0.59, Kappa: 0.20,  AUC: 0.63, Sensitivity: 0.73, Specificity: 0.47

 # // 3 variable (dist, margin, three_pt) as baseline going forward //

```



```{r Naive Bayes}
 
 # 5 features
model_nb <- naive_bayes(as.factor(result) ~ distance_ft + qtr + sec_remaining + margin + three_pt,
                        data = train_df,
                        laplace = 1)
 # NB model EDA (top 3 features)
model_nb$tables$distance_ft
model_nb$tables$margin
model_nb$tables$three_pt

preds_nb = predict(model_nb,
                   newdata = test_df,
                   type = 'class')
probs_nb = predict(model_nb,
                   newdata = test_df,
                   type = 'prob')[, 2]

roc_nb <- roc(test_df$result, probs_nb)
cat("Naive Bayes AUC:", auc(roc_nb), "\n")

confusionMatrix(as.factor(preds_nb), as.factor(test_df$result))

 # 3 features
model_nb <- naive_bayes(as.factor(result) ~ distance_ft + margin + three_pt,
                        data = train_df,
                        laplace = 1)

preds_nb = predict(model_nb,
                   newdata = test_df,
                   type = 'class')
probs_nb = predict(model_nb,
                   newdata = test_df,
                   type = 'prob')[, 2]

roc_nb <- roc(test_df$result, probs_nb)
cat("Naive Bayes AUC:", auc(roc_nb), "\n")

confusionMatrix(as.factor(preds_nb), as.factor(test_df$result))

 # NB feature comparison

 # 5 variable (dist, qtr, sec, margin, three_pt)    Accuracy: 0.59, Kappa: 0.18, AUC: 0.63, Sensitivity: 0.71, Specificity: 0.47
 # 3 variable (dist, margin, three_pt)              Accuracy: 0.59, Kappa: 0.19, AUC: 0.64, Sensitivity: 0.71, Specificity: 0.49

 # // 3 variable (dist, margin, three_pt) //

```





```{r Define Clutch}

# iterate later : 
#   
#   clutch_df <- curry
#          is_clutch = ifelse(
#            qtr %in% c('4th Qtr', '1st OT', '2nd OT') &
#              sec_remaining <= 120 &
#              margin <= 5,
#            1, 0)
#          ) |>

```

